import { Icons } from "../components/icons";

export const pageLinks = [
  { title: "Dashboard", icon: <Icons.dashboard /> },
  { title: "Demand Planning", icon: <Icons.plan /> },
  { title: "Purchase Orders", icon: <Icons.orders /> },
  { title: "Back Orders", icon: <Icons.back /> },
  { title: "Products", icon: <Icons.products /> },
  { title: "Suppliers", icon: <Icons.supplies /> },
  { title: "Alerts", icon: <Icons.warning /> },
  { title: "Notification", icon: <Icons.bell /> },
  { title: "Profile", icon: <Icons.user /> },
];

const products = [
  {
    product: { name: "Men’s shoes", color: "Red/09", price: "AU$120", img: "" },
    classify: "A",
    time: "3 days",
    cost: "AU$50",
    level: "37 units",
    unit: "10",
    holding_cost: "35",
  },
  {
    product: { name: "Men’s shoes", color: "Red/09", price: "AU$120", img: "" },
    classify: "B",
    time: "3 days",
    cost: "AU$150",
    level: "37 units",
    unit: "10",
    holding_cost: "35",
  },
  {
    product: { name: "Men’s shoes", color: "Red/09", price: "AU$120", img: "" },
    classify: "A",
    time: "3 days",
    cost: "AU$50",
    level: "37 units",
    unit: "",
    holding_cost: "",
  },
  {
    product: { name: "Men’s shoes", color: "Red/09", price: "AU$120", img: "" },
    classify: "A",
    time: "3 days",
    cost: "AU$80",
    level: "37 units",
    unit: "",
    holding_cost: "35",
  },
  {
    product: { name: "Men’s shoes", color: "Red/09", price: "AU$120", img: "" },
    classify: "A",
    time: "3 days",
    cost: "AU$50",
    level: "37 units",
    unit: "10",
    holding_cost: "35",
  },
  {
    product: { name: "Men’s shoes", color: "Red/09", price: "AU$120", img: "" },
    classify: "B",
    time: "3 days",
    cost: "AU$150",
    level: "37 units",
    unit: "10",
    holding_cost: "35",
  },
  {
    product: { name: "Men’s shoes", color: "Red/09", price: "AU$120", img: "" },
    classify: "A",
    time: "3 days",
    cost: "AU$50",
    level: "37 units",
    unit: "",
    holding_cost: "",
  },
  {
    product: { name: "Men’s shoes", color: "Red/09", price: "AU$120", img: "" },
    classify: "A",
    time: "3 days",
    cost: "AU$80",
    level: "37 units",
    unit: "",
    holding_cost: "35",
  },
  {
    product: { name: "Men’s shoes", color: "Red/09", price: "AU$120", img: "" },
    classify: "A",
    time: "3 days",
    cost: "AU$50",
    level: "37 units",
    unit: "10",
    holding_cost: "35",
  },
  {
    product: { name: "Men’s shoes", color: "Red/09", price: "AU$120", img: "" },
    classify: "B",
    time: "3 days",
    cost: "AU$150",
    level: "37 units",
    unit: "10",
    holding_cost: "35",
  },
  {
    product: { name: "Men’s shoes", color: "Red/09", price: "AU$120", img: "" },
    classify: "A",
    time: "3 days",
    cost: "AU$50",
    level: "37 units",
    unit: "",
    holding_cost: "",
  },
  {
    product: { name: "Men’s shoes", color: "Red/09", price: "AU$120", img: "" },
    classify: "A",
    time: "3 days",
    cost: "AU$80",
    level: "37 units",
    unit: "",
    holding_cost: "35",
  },
  {
    product: { name: "Men’s shoes", color: "Red/09", price: "AU$120", img: "" },
    classify: "A",
    time: "3 days",
    cost: "AU$50",
    level: "37 units",
    unit: "10",
    holding_cost: "35",
  },
  {
    product: { name: "Men’s shoes", color: "Red/09", price: "AU$120", img: "" },
    classify: "B",
    time: "3 days",
    cost: "AU$150",
    level: "37 units",
    unit: "10",
    holding_cost: "35",
  },
  {
    product: { name: "Men’s shoes", color: "Red/09", price: "AU$120", img: "" },
    classify: "A",
    time: "3 days",
    cost: "AU$50",
    level: "37 units",
    unit: "",
    holding_cost: "",
  },
  {
    product: { name: "Men’s shoes", color: "Red/09", price: "AU$120", img: "" },
    classify: "A",
    time: "3 days",
    cost: "AU$80",
    level: "37 units",
    unit: "",
    holding_cost: "35",
  },
  {
    product: { name: "Men’s shoes", color: "Red/09", price: "AU$120", img: "" },
    classify: "A",
    time: "3 days",
    cost: "AU$50",
    level: "37 units",
    unit: "10",
    holding_cost: "35",
  },
  {
    product: { name: "Men’s shoes", color: "Red/09", price: "AU$120", img: "" },
    classify: "B",
    time: "3 days",
    cost: "AU$150",
    level: "37 units",
    unit: "10",
    holding_cost: "35",
  },
  {
    product: { name: "Men’s shoes", color: "Red/09", price: "AU$120", img: "" },
    classify: "A",
    time: "3 days",
    cost: "AU$50",
    level: "37 units",
    unit: "",
    holding_cost: "",
  },
  {
    product: { name: "Men’s shoes", color: "Red/09", price: "AU$120", img: "" },
    classify: "A",
    time: "3 days",
    cost: "AU$80",
    level: "37 units",
    unit: "",
    holding_cost: "35",
  },
  {
    product: { name: "Men’s shoes", color: "Red/09", price: "AU$120", img: "" },
    classify: "A",
    time: "3 days",
    cost: "AU$50",
    level: "37 units",
    unit: "10",
    holding_cost: "35",
  },
  {
    product: { name: "Men’s shoes", color: "Red/09", price: "AU$120", img: "" },
    classify: "B",
    time: "3 days",
    cost: "AU$150",
    level: "37 units",
    unit: "10",
    holding_cost: "35",
  },
  {
    product: { name: "Men’s shoes", color: "Red/09", price: "AU$120", img: "" },
    classify: "A",
    time: "3 days",
    cost: "AU$50",
    level: "37 units",
    unit: "",
    holding_cost: "",
  },
  {
    product: { name: "Men’s shoes", color: "Red/09", price: "AU$120", img: "" },
    classify: "A",
    time: "3 days",
    cost: "AU$80",
    level: "37 units",
    unit: "",
    holding_cost: "35",
  },
  {
    product: { name: "Men’s shoes", color: "Red/09", price: "AU$120", img: "" },
    classify: "A",
    time: "3 days",
    cost: "AU$50",
    level: "37 units",
    unit: "10",
    holding_cost: "35",
  },
  {
    product: { name: "Men’s shoes", color: "Red/09", price: "AU$120", img: "" },
    classify: "B",
    time: "3 days",
    cost: "AU$150",
    level: "37 units",
    unit: "10",
    holding_cost: "35",
  },
  {
    product: { name: "Men’s shoes", color: "Red/09", price: "AU$120", img: "" },
    classify: "A",
    time: "3 days",
    cost: "AU$50",
    level: "37 units",
    unit: "",
    holding_cost: "",
  },
  {
    product: { name: "Men’s shoes", color: "Red/09", price: "AU$120", img: "" },
    classify: "A",
    time: "3 days",
    cost: "AU$80",
    level: "37 units",
    unit: "",
    holding_cost: "35",
  },
  {
    product: { name: "Men’s shoes", color: "Red/09", price: "AU$120", img: "" },
    classify: "A",
    time: "3 days",
    cost: "AU$50",
    level: "37 units",
    unit: "10",
    holding_cost: "35",
  },
  {
    product: { name: "Men’s shoes", color: "Red/09", price: "AU$120", img: "" },
    classify: "B",
    time: "3 days",
    cost: "AU$150",
    level: "37 units",
    unit: "10",
    holding_cost: "35",
  },
  {
    product: { name: "Men’s shoes", color: "Red/09", price: "AU$120", img: "" },
    classify: "A",
    time: "3 days",
    cost: "AU$50",
    level: "37 units",
    unit: "",
    holding_cost: "",
  },
  {
    product: { name: "Men’s shoes", color: "Red/09", price: "AU$120", img: "" },
    classify: "A",
    time: "3 days",
    cost: "AU$80",
    level: "37 units",
    unit: "",
    holding_cost: "35",
  },
  {
    product: { name: "Men’s shoes", color: "Red/09", price: "AU$120", img: "" },
    classify: "A",
    time: "3 days",
    cost: "AU$50",
    level: "37 units",
    unit: "10",
    holding_cost: "35",
  },
  {
    product: { name: "Men’s shoes", color: "Red/09", price: "AU$120", img: "" },
    classify: "B",
    time: "3 days",
    cost: "AU$150",
    level: "37 units",
    unit: "10",
    holding_cost: "35",
  },
  {
    product: { name: "Men’s shoes", color: "Red/09", price: "AU$120", img: "" },
    classify: "A",
    time: "3 days",
    cost: "AU$50",
    level: "37 units",
    unit: "",
    holding_cost: "",
  },
  {
    product: { name: "Men’s shoes", color: "Red/09", price: "AU$120", img: "" },
    classify: "A",
    time: "3 days",
    cost: "AU$80",
    level: "37 units",
    unit: "",
    holding_cost: "35",
  },
];

export const duplicate_items = [
  ...products,
  ...products,
  ...products,
  ...products,
  ...products,
  ...products,
  ...products,
  ...products,
];
